spring.datasource.url= jdbc:mysql://localhost:3306/bankingapp_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto= update

spring.mail.host=smtp.gmail.com
spring.mail.port=465

#sender email
spring.mail.username=sindhujabollikonda@gmail.com
#from gmail crete a key
spring.mail.password=umhvcurrmgopoxfv
spring.mail.properties.mail.smtp.auth= true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

#search generate 256 bit secret key jwt in browser and generate random 256 bit
app.jwt-secert= YmVjb21pbmdkb3VibGV5b3Vyc2VsZmdvdHN1bmFnb2RyZXdvaWxzb2FwZGlncGVyaGE=
#24 hrs = 86400000ms
app.jwt-expiration=86400000

